version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: '${API_PORT:-3000}'
    image: job-board/node
    ports:
      - "3000:${API_PORT:-3000}"
    command: sh -c "dockerize -wait tcp://mysql:3306 -timeout 300s -wait-retry-interval 5s yarn start:server"
    networks:
      - app-network
    depends_on:
      - mysql
  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    image: job-board/mysql
    env_file: .env
    volumes:
      - dbdata:/var/lib/mysql
    expose:
      - '3306'
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  dbdata: