version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
      args:
        PORT: '${API_PORT:-3000}'
    image: job-board/node:prod
    ports:
      - "3000:${API_PORT:-3000}"
    command: sh -c "dockerize -wait tcp://mysql:3306 -timeout 300s -wait-retry-interval 5s yarn start:server"
    networks:
      - app-network
    depends_on:
      - mysql
      - es-master
      - es-data-1
  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    image: job-board/mysql
    env_file: .env
    volumes:
      - dbdata:/var/lib/mysql
    expose:
      - '3306'
    networks:
      - app-network
  es-master:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.16
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - app-network
  es-data-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.16
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=es-master"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - app-network
    depends_on:
      - es-master
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
  esdata1:
  esdata2:
