version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:${PORT}"
    volumes:
      - .:/usr/src/app
    command: "yarn start:server:dev"
    networks:
      - app-network
  mysql:
    image: "mysql:5.7"
    env_file: .env
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - '3306'
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  dbdata: