version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:${PORT}"
      - "3001:3001"
    volumes:
      - .:/usr/src/app
    command: sh -c "dockerize -wait tcp://mysql:3306 -timeout 300s -wait-retry-interval 5s yarn start:server:dev"
    networks:
      - app-network
    depends_on:
      - mysql
  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - '3306'
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  dbdata: